### PR TITLE
Switch to MongoDB 3.2

### PR DESCRIPTION
**Pull request by jvrplmlmn**
> Resolves https://github.com/StackStorm/chef-stackstorm/issues/8

Haven't tested this with Ubuntu, but it is working on CentOS 7.2

@shortdudey123 @sysbot would you guys mind taking a look?

### CODE REVIEW

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1473188004000221

**Comment by jvrplmlmn** [comment]
Ran KitchenCI on both CentOS and Ubuntu and it worked. Tomorrow I'll bump the version of the cookbook and merge the changes.

**Comment by shortdudey123** [comment]
👍  we should probably released `0.4.0` after merging this

**Comment by jvrplmlmn** [comment]
@shortdudey123 @armab which release workflow are we using for this cookbook? We merge and then bump the version on master (or in another PR just for that)?

**Pull request merged**
