### PR TITLE
Move Tests to Unit and Integration dirs

### PR DESCRIPTION
**Pull request by arm4b**
As mentioned in #29
Use the following directory structure for tests: 

* `test/unit/...` - ChefSpec
* `test/integration/...` - InSpec

I noticed that some official Chef cookbooks use it, so it looks like acceptable, just a matter of preference.

This makes things more straightforward, especially for less experienced Chef users (entire StackStorm team, including me). And since we're going to officially support this installation method, simplicity is preferred.

### CODE REVIEW

**Comment by shortdudey123** [comment]
> some official Chef cookbooks

Not sure where you see this since `spec/` is the typical path

**Comment by shortdudey123** [comment]
Looks like `spec/` is the preferred path

Directory structure from `chef generate cookbook test` which is the correct way to create a new cookbook stub

```
test
├── Berksfile
├── README.md
├── chefignore
├── metadata.rb
├── recipes
│   └── default.rb
├── spec
│   ├── spec_helper.rb
│   └── unit
│       └── recipes
│           └── default_spec.rb
└── test
    └── recipes
        └── default_test.rb

6 directories, 8 files
```

**Comment by arm4b** [comment]
Yes, of course the default is `spec/`. 

But it's configurable and a matter of preference. Ideally I'd like to have the following structure to avoid any confusion maintaining this repo and identifying where are tests from our support.

Here is more explicit naming: 

as seen in some cookbooks.

@sysbot @jvrplmlmn WDYT guys?

**Comment by shortdudey123** [comment]
I am 👎 👎 👎  on this since it is fairly non-standard.
FWIW, the referenced cookbook (crowd) is not an official chef-cookbook like mentioned
Also, `spec/` appears to be the standard in the `StackStorm` org repos (unless that is changing everywhere and this is just the first one)

I will let others look at this and add their input

**Comment by jvrplmlmn** [comment]
I do not have a strong opinion about this, as long as we are testing :trollface: 

Using the tools included in the ChefDK to generate cookbooks, shows that `spec` is usually in the root directory of the cookbook and other tests are under `test` (integration, fixtures, cookbook-examples, ...).

For reference:

```
➜  /tmp chef generate cookbook example
Generating cookbook example
- Ensuring correct cookbook file content
- Committing cookbook files to git
- Ensuring delivery configuration
- Ensuring correct delivery build cookbook content
- Adding delivery configuration to feature branch
- Adding build cookbook to feature branch
- Merging delivery content feature branch to master

Your cookbook is ready. Type `cd example` to enter it.

There are several commands you can run to get started locally developing and testing your cookbook.
Type `delivery local --help` to see a full list.

Why not start by writing a test? Tests for the default recipe are stored at:

test/recipes/default_test.rb

If you'd prefer to dive right in, the default recipe can be found at:

recipes/default.rb

➜  /tmp tree example
example
├── Berksfile
├── README.md
├── chefignore
├── metadata.rb
├── recipes
│   └── default.rb
├── spec
│   ├── spec_helper.rb
│   └── unit
│       └── recipes
│           └── default_spec.rb
└── test
    └── recipes
        └── default_test.rb

6 directories, 8 files
➜  /tmp
```

Most cookbooks in https://github.com/chef-cookbooks also follow this pattern.

**Comment by arm4b** [comment]
Decided!
Thanks guys for your opinion :+1: 

Moving forward to next thing.

**Pull request closed without merging**
