### PR TITLE
Drop Fedora support. Distro not officially supported by Stackstorm.

### PR DESCRIPTION
**Pull request by jvrplmlmn**
Resolves stackstorm/chef-stackstorm#12

@shortdudey123 @armab ?

### CODE REVIEW

**Comment by jvrplmlmn** [comment]
There is still some remaining conditional code that only applies for Fedora. Should we drop that as well or we just don't test for that distribution?

**Comment by arm4b** [comment]
:+1: for dropping everything that relates to Fedora

**Comment by jvrplmlmn** [comment]
@armab done

**Comment by arm4b** [comment]
@jvrplmlmn Thanks!
Makes things much cleaner.

**Comment by shortdudey123** [comment]
👍  looking good

**Pull request merged**
