### PR TITLE
Add FoodCritic and Rubocop testing

### PR DESCRIPTION
**Pull request by shortdudey123**

### CODE REVIEW

**Comment by arm4b** [comment]
@shortdudey123 this is really nice, but these recipes (incl. https://github.com/StackStorm/chef-openstack-mistral) are really outdated and codify old installation way, which is not supported anymore.

Entire installation [was reworked](https://stackstorm.com/2016/05/03/road-to-packages/), where all pip requirements are already bundled in `deb/rpm` native packages.

You can use the following (fresh) instructions to install StackStorm: https://docs.stackstorm.com/install/index.html

**Comment by shortdudey123** [comment]
@armab i am aware of that, one step at a time :)
That part will be in another PR once this repo is a bit more standardized

**Comment by arm4b** [comment]
Awesome! :+1:

**Comment by arm4b** [comment]
And sorry for this confuse, because we should place some notice beforehand, indicating that repo is outdated/requires re-work after we released new packages.

**Comment by shortdudey123** [comment]
np

**Comment by shortdudey123** [comment]
Let me know you feedback on the updates here
If you guys have travis turned on for this repo (or want to turn it on) then i can add a `.travis.yml` file as well

**Comment by Kami** [comment]
@shortdudey123 Yeah, please add `.travis.yml` file and I will enable Travis for this repo.

Thanks!

**Comment by enykeev** [comment]
I've enabled it. Now we only need a file.

**Comment by shortdudey123** [comment]
@Kami @enykeev all done :)

**Comment by dennybaa** [comment]
@shortdudey123 Thank you! Looks good) @Kami @enykeev, I'm +1 to merge this.

**Comment by Kami** [comment]
Merged, thanks!

**Pull request merged**
